export const theme = {
  primary: '#f59e0b',
  primaryDark: '#d97706',
  danger: '#ef4444',
  success: '#22c55e',
  bg: '#f9fafb',
  white: '#ffffff',
  border: '#e5e7eb',
  text: '#111827',
  muted: '#6b7280',
};

export const styles = {
  page: {
    minHeight: '100vh',
    background: theme.bg,
    fontFamily: 'system-ui, sans-serif',
    color: theme.text,
  },
  card: {
    background: theme.white,
    borderRadius: 8,
    padding: 24,
    boxShadow: '0 1px 4px rgba(0,0,0,0.1)',
    border: `1px solid ${theme.border}`,
  },
  input: {
    width: '100%',
    padding: '10px 12px',
    border: `1px solid ${theme.border}`,
    borderRadius: 6,
    fontSize: 14,
    outline: 'none',
    boxSizing: 'border-box',
  },
  button: {
    padding: '10px 20px',
    background: theme.primary,
    color: theme.white,
    border: 'none',
    borderRadius: 6,
    cursor: 'pointer',
    fontWeight: 600,
    fontSize: 14,
  },
  dangerButton: {
    padding: '6px 14px',
    background: theme.danger,
    color: theme.white,
    border: 'none',
    borderRadius: 6,
    cursor: 'pointer',
    fontSize: 13,
  },
  nav: {
    background: theme.white,
    borderBottom: `1px solid ${theme.border}`,
    padding: '12px 24px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    boxShadow: '0 1px 3px rgba(0,0,0,0.05)',
  },
  label: {
    display: 'block',
    fontSize: 13,
    fontWeight: 600,
    marginBottom: 6,
    color: theme.text,
  },
  error: {
    background: '#fef2f2',
    border: '1px solid #fecaca',
    color: '#dc2626',
    padding: '10px 14px',
    borderRadius: 6,
    fontSize: 14,
  },
  success: {
    background: '#f0fdf4',
    border: '1px solid #bbf7d0',
    color: '#16a34a',
    padding: '10px 14px',
    borderRadius: 6,
    fontSize: 14,
  },
};
